# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.25.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.25.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Volumes/Data/sketching/mglyphs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Volumes/Data/sketching/mglyphs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.25.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.25.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.25.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.25.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.25.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.25.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.25.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.25.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	cd /Volumes/Data/sketching/mglyphs && $(CMAKE_COMMAND) -E cmake_progress_start /Volumes/Data/sketching/mglyphs/CMakeFiles /Volumes/Data/sketching/mglyphs/externals/diatonic//CMakeFiles/progress.marks
	cd /Volumes/Data/sketching/mglyphs && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 externals/diatonic/all
	$(CMAKE_COMMAND) -E cmake_progress_start /Volumes/Data/sketching/mglyphs/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /Volumes/Data/sketching/mglyphs && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 externals/diatonic/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /Volumes/Data/sketching/mglyphs && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 externals/diatonic/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /Volumes/Data/sketching/mglyphs && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 externals/diatonic/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /Volumes/Data/sketching/mglyphs && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
externals/diatonic/CMakeFiles/diatonic.dir/rule:
	cd /Volumes/Data/sketching/mglyphs && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 externals/diatonic/CMakeFiles/diatonic.dir/rule
.PHONY : externals/diatonic/CMakeFiles/diatonic.dir/rule

# Convenience name for target.
diatonic: externals/diatonic/CMakeFiles/diatonic.dir/rule
.PHONY : diatonic

# fast build rule for target.
diatonic/fast:
	cd /Volumes/Data/sketching/mglyphs && $(MAKE) $(MAKESILENT) -f externals/diatonic/CMakeFiles/diatonic.dir/build.make externals/diatonic/CMakeFiles/diatonic.dir/build
.PHONY : diatonic/fast

# Convenience name for target.
externals/diatonic/CMakeFiles/diatonic_demo.dir/rule:
	cd /Volumes/Data/sketching/mglyphs && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 externals/diatonic/CMakeFiles/diatonic_demo.dir/rule
.PHONY : externals/diatonic/CMakeFiles/diatonic_demo.dir/rule

# Convenience name for target.
diatonic_demo: externals/diatonic/CMakeFiles/diatonic_demo.dir/rule
.PHONY : diatonic_demo

# fast build rule for target.
diatonic_demo/fast:
	cd /Volumes/Data/sketching/mglyphs && $(MAKE) $(MAKESILENT) -f externals/diatonic/CMakeFiles/diatonic_demo.dir/build.make externals/diatonic/CMakeFiles/diatonic_demo.dir/build
.PHONY : diatonic_demo/fast

examples/main.o: examples/main.cpp.o
.PHONY : examples/main.o

# target to build an object file
examples/main.cpp.o:
	cd /Volumes/Data/sketching/mglyphs && $(MAKE) $(MAKESILENT) -f externals/diatonic/CMakeFiles/diatonic_demo.dir/build.make externals/diatonic/CMakeFiles/diatonic_demo.dir/examples/main.cpp.o
.PHONY : examples/main.cpp.o

examples/main.i: examples/main.cpp.i
.PHONY : examples/main.i

# target to preprocess a source file
examples/main.cpp.i:
	cd /Volumes/Data/sketching/mglyphs && $(MAKE) $(MAKESILENT) -f externals/diatonic/CMakeFiles/diatonic_demo.dir/build.make externals/diatonic/CMakeFiles/diatonic_demo.dir/examples/main.cpp.i
.PHONY : examples/main.cpp.i

examples/main.s: examples/main.cpp.s
.PHONY : examples/main.s

# target to generate assembly for a file
examples/main.cpp.s:
	cd /Volumes/Data/sketching/mglyphs && $(MAKE) $(MAKESILENT) -f externals/diatonic/CMakeFiles/diatonic_demo.dir/build.make externals/diatonic/CMakeFiles/diatonic_demo.dir/examples/main.cpp.s
.PHONY : examples/main.cpp.s

src/chords.o: src/chords.cpp.o
.PHONY : src/chords.o

# target to build an object file
src/chords.cpp.o:
	cd /Volumes/Data/sketching/mglyphs && $(MAKE) $(MAKESILENT) -f externals/diatonic/CMakeFiles/diatonic.dir/build.make externals/diatonic/CMakeFiles/diatonic.dir/src/chords.cpp.o
.PHONY : src/chords.cpp.o

src/chords.i: src/chords.cpp.i
.PHONY : src/chords.i

# target to preprocess a source file
src/chords.cpp.i:
	cd /Volumes/Data/sketching/mglyphs && $(MAKE) $(MAKESILENT) -f externals/diatonic/CMakeFiles/diatonic.dir/build.make externals/diatonic/CMakeFiles/diatonic.dir/src/chords.cpp.i
.PHONY : src/chords.cpp.i

src/chords.s: src/chords.cpp.s
.PHONY : src/chords.s

# target to generate assembly for a file
src/chords.cpp.s:
	cd /Volumes/Data/sketching/mglyphs && $(MAKE) $(MAKESILENT) -f externals/diatonic/CMakeFiles/diatonic.dir/build.make externals/diatonic/CMakeFiles/diatonic.dir/src/chords.cpp.s
.PHONY : src/chords.cpp.s

src/intervals.o: src/intervals.cpp.o
.PHONY : src/intervals.o

# target to build an object file
src/intervals.cpp.o:
	cd /Volumes/Data/sketching/mglyphs && $(MAKE) $(MAKESILENT) -f externals/diatonic/CMakeFiles/diatonic.dir/build.make externals/diatonic/CMakeFiles/diatonic.dir/src/intervals.cpp.o
.PHONY : src/intervals.cpp.o

src/intervals.i: src/intervals.cpp.i
.PHONY : src/intervals.i

# target to preprocess a source file
src/intervals.cpp.i:
	cd /Volumes/Data/sketching/mglyphs && $(MAKE) $(MAKESILENT) -f externals/diatonic/CMakeFiles/diatonic.dir/build.make externals/diatonic/CMakeFiles/diatonic.dir/src/intervals.cpp.i
.PHONY : src/intervals.cpp.i

src/intervals.s: src/intervals.cpp.s
.PHONY : src/intervals.s

# target to generate assembly for a file
src/intervals.cpp.s:
	cd /Volumes/Data/sketching/mglyphs && $(MAKE) $(MAKESILENT) -f externals/diatonic/CMakeFiles/diatonic.dir/build.make externals/diatonic/CMakeFiles/diatonic.dir/src/intervals.cpp.s
.PHONY : src/intervals.cpp.s

src/scales.o: src/scales.cpp.o
.PHONY : src/scales.o

# target to build an object file
src/scales.cpp.o:
	cd /Volumes/Data/sketching/mglyphs && $(MAKE) $(MAKESILENT) -f externals/diatonic/CMakeFiles/diatonic.dir/build.make externals/diatonic/CMakeFiles/diatonic.dir/src/scales.cpp.o
.PHONY : src/scales.cpp.o

src/scales.i: src/scales.cpp.i
.PHONY : src/scales.i

# target to preprocess a source file
src/scales.cpp.i:
	cd /Volumes/Data/sketching/mglyphs && $(MAKE) $(MAKESILENT) -f externals/diatonic/CMakeFiles/diatonic.dir/build.make externals/diatonic/CMakeFiles/diatonic.dir/src/scales.cpp.i
.PHONY : src/scales.cpp.i

src/scales.s: src/scales.cpp.s
.PHONY : src/scales.s

# target to generate assembly for a file
src/scales.cpp.s:
	cd /Volumes/Data/sketching/mglyphs && $(MAKE) $(MAKESILENT) -f externals/diatonic/CMakeFiles/diatonic.dir/build.make externals/diatonic/CMakeFiles/diatonic.dir/src/scales.cpp.s
.PHONY : src/scales.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... diatonic"
	@echo "... diatonic_demo"
	@echo "... examples/main.o"
	@echo "... examples/main.i"
	@echo "... examples/main.s"
	@echo "... src/chords.o"
	@echo "... src/chords.i"
	@echo "... src/chords.s"
	@echo "... src/intervals.o"
	@echo "... src/intervals.i"
	@echo "... src/intervals.s"
	@echo "... src/scales.o"
	@echo "... src/scales.i"
	@echo "... src/scales.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /Volumes/Data/sketching/mglyphs && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

